## Imports

In [61]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Checking the first sample

In [2]:
# Long running
y, x = load_data(train=True)
print(f"First sample: {x[0,:]}")
print(f"First sample label: {y[0]}")

First sample: [ 1.38470e+02  5.16550e+01  9.78270e+01  2.79800e+01  9.10000e-01
  1.24711e+02  2.66600e+00  3.06400e+00  4.19280e+01  1.97760e+02
  1.58200e+00  1.39600e+00  2.00000e-01  3.26380e+01  1.01700e+00
  3.81000e-01  5.16260e+01  2.27300e+00 -2.41400e+00  1.68240e+01
 -2.77000e-01  2.58733e+02  2.00000e+00  6.74350e+01  2.15000e+00
  4.44000e-01  4.60620e+01  1.24000e+00 -2.47500e+00  1.13497e+02]
First sample label: 1


## Tests

In [3]:
# Define some test data
testing_y = np.array([1,1,2,2,4])
testing_x = np.array([[1],[2],[3],[4],[5]])
testing_w = np.array([-0.1, 0.7])

print(f"X:\n {testing_x}\n")
testing_sx, testing_mean_x, testing_std_x = standardize(testing_x) # Standardization
print(f"X normalized:\n {testing_sx}\n") 
testing_tx = add_x_bias(testing_sx) # Adding bias column to X
print(f"X with bias:\n {testing_tx}")


X:
 [[1]
 [2]
 [3]
 [4]
 [5]]

X normalized:
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

X with bias:
 [[ 1.         -1.41421356]
 [ 1.         -0.70710678]
 [ 1.          0.        ]
 [ 1.          0.70710678]
 [ 1.          1.41421356]]


### MSE

In [4]:
print("MSE TEST")
print(f"Got:{compute_mse(testing_y, testing_tx, testing_w)}")
print("Expected:" + str(4.71))

MSE TEST
Got:4.714070708874368
Expected:4.71


### MAE

In [5]:
print("MAE TEST")
print(f"Got:{compute_mae(testing_y, testing_tx, testing_w)}")
print("Expected:" + str(2.1))

MAE TEST
Got:2.1
Expected:2.1


### MSE Gradient

In [6]:
print("MSE Gradient TEST")
print(f"Got:{compute_mse_gradient(testing_y, testing_tx, testing_w)}")
print("Expected:" + str([-2.1, -0.29]))

MSE Gradient TEST
Got:[-2.1        -0.28994949]
Expected:[-2.1, -0.29]


### MAE Gradient

In [7]:
print("MAE Gradient TEST")
print(f"Got:{compute_mae_gradient(testing_y, testing_tx, testing_w)}")
print("Expected:" + str([-1, -0]))

MAE Gradient TEST
Got:[-1.  0.]
Expected:[-1, 0]


## Assignment

### Pre-processing

In [78]:
y_tr, x_tr = load_data(train=True) # Load train data
y_te, x_te = load_data(train=False) # Load test data
x_tr = replace_min_999_by_col_mean(x_tr) # Handle invalid values
x_te = replace_min_999_by_col_mean(x_te)

x_tr, mean_x_tr, std_x_tr = standardize(x_tr) # Standardize x
x_te, mean_x_te, std_x_te = standardize(x_te)

tx_tr = build_poly(x_tr, 2) # build polynomial expansion (with bias)
tx_te = build_poly(x_te, 2)

### Linear regression using gradient descent

In [ ]:
# We run GD step times per epoch, for epochs epochs (same as running GD for epochs*step just lets us print intermediate results)
w, epochs, step, gamma = np.zeros(61), 100, 100, 1e-4
loss_tr_GD = []
loss_te_GD = []
for i in range((int)(epochs)):
    w, loss_tr = least_squares_GD(y_tr, tx_tr, w, step, gamma)
    loss_te = compute_mse(y_te, tx_te, w)
    loss_tr_GD.append(loss_tr)
    loss_te_GD.append(loss_te)
    print(f"Epoch {i} : Training loss: {loss_tr} Test loss: {loss_te}")

Epoch 0 : Training loss: 0.28653501985302926 Test loss: 0.8568301408047532
Epoch 1 : Training loss: 0.2646759091502792 Test loss: 0.787958207087495
Epoch 2 : Training loss: 0.25188103877212425 Test loss: 0.7436585475593934
Epoch 3 : Training loss: 0.24289694588171118 Test loss: 0.710779876106066
Epoch 4 : Training loss: 0.236007111749431 Test loss: 0.6845113922487513
Epoch 5 : Training loss: 0.23047164244235122 Test loss: 0.6626982526003737
Epoch 6 : Training loss: 0.22589730737860683 Test loss: 0.6441895309927617
Epoch 7 : Training loss: 0.22204050536862108 Test loss: 0.6282748733801345
Epoch 8 : Training loss: 0.21873530797490556 Test loss: 0.6144673396874024
Epoch 9 : Training loss: 0.21586259032879546 Test loss: 0.6024087586331878
Epoch 10 : Training loss: 0.21333429913990562 Test loss: 0.5918231649854439
Epoch 11 : Training loss: 0.2110841639748312 Test loss: 0.5824912315285625
Epoch 12 : Training loss: 0.20906164226856097 Test loss: 0.5742348644669887
Epoch 13 : Training loss: 0.

In [ ]:
plt.plot(range(len(loss_tr_GD)), loss_tr_GD, c='red')
plt.plot(range(len(loss_te_GD)), loss_te_GD, c='blue')

### Linear regression using stochastic gradient descent

In [81]:
w, epochs, step, gamma = np.zeros(61), 100, 100, 1e-4
for i in range((int)(epochs)):
    w, loss_tr = least_squares_SGD(y_tr, tx_tr, w, step, gamma)
    loss_te = compute_mse(y_te, tx_te, w)
    print(f"Epoch {i} : Training loss: {loss_tr} Test loss: {loss_te}")

(250000, 61)
(250000,)
Epoch 0 : Training loss: 0.3325976914081756 Test loss: 0.976277911177939
Epoch 1 : Training loss: 0.3238842786537892 Test loss: 0.9557873361616362
Epoch 2 : Training loss: 0.3093048577740203 Test loss: 0.9260135398804302
Epoch 3 : Training loss: 0.30277042163268175 Test loss: 0.8993444583511248
Epoch 4 : Training loss: 0.2972807172571732 Test loss: 0.8773530529238618
Epoch 5 : Training loss: 0.2969855940673768 Test loss: 0.87961412482193
Epoch 6 : Training loss: 0.29427432382864666 Test loss: 0.8700675569943024
Epoch 7 : Training loss: 0.29370545598339304 Test loss: 0.8582892691605222
Epoch 8 : Training loss: 0.29282889551435326 Test loss: 0.8381590945025345
Epoch 9 : Training loss: 0.2924761487162052 Test loss: 0.8362876407143413
Epoch 10 : Training loss: 0.2923654915277618 Test loss: 0.8159807116154717
Epoch 11 : Training loss: 0.2878650679929162 Test loss: 0.8335701158078369
Epoch 12 : Training loss: 0.28338901580415593 Test loss: 0.8293527695870646
Epoch 13 :

### Least squares

In [56]:
w, loss_tr = least_squares(y_tr, tx_tr)
loss_te = compute_mse(y_te, tx_te, w)
print(f"Training loss: {loss_tr}\nTest loss: {loss_te}\nw: {w}")

LinAlgError: Singular matrix

### Ridge regression

In [43]:
lambda_ = 0.1
w, loss_tr = ridge_regression(y_tr, tx_tr, lambda_)
print(f"Training loss: {loss}\n")

Training loss: 0.17758079539317778



### Logistic regression using gradient descent or SGD (y ∈ {0, 1})

### Regularized logistic regression using gradient descent or SGD (y ∈ {0, 1}, with regularization term λ∥w∥**2)